'use client';
import { useState } from 'react';
import { Search, SlidersHorizontal, X } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Pick, Field } from './fields';
import { Filters, Snapshot, EMPTY_FILTERS, MODULES, display, levelNames, filterLabels } from './model';
export function FilterPanel({ filters: f, data, onChange }: {
    filters: Filters;
    data: Snapshot;
    onChange: (v: Filters) => void;
}) {
    const [more, setMore] = useState(false);
    const set = (key: keyof Filters, value: string) => onChange({ ...f, [key]: value, ...(key === 'course' ? { batch: 'all' } : {}) });
    const all = { value: 'all', label: 'All' };
    const labels = filterLabels(f, data);
    return <div className="filter-panel"><div className="filter-top"><div className="search-box"><Search size={18}/><Input aria-label="Search students" placeholder="Search name, student ID, phone or batch…" value={f.search} onChange={e => set('search', e.target.value)}/></div><Button variant={more ? 'secondary' : 'outline'} aria-expanded={more} onClick={() => setMore(!more)}><SlidersHorizontal size={16}/> More filters {labels.length > 0 && <span className="count-pill">{labels.length}</span>}</Button></div><div className="quick-filters"><Pick label="Course" value={f.course} onChange={v => set('course', v)} options={[{ ...all, label: 'All courses' }, ...data.courses.map(c => ({ value: c.id, label: c.name }))]}/><Pick label="Batch" value={f.batch} onChange={v => set('batch', v)} options={[{ ...all, label: 'All batches' }, ...data.batches.filter(b => f.course === 'all' || b.course_type_id === f.course).map(b => ({ value: b.id, label: b.batch_code }))]}/><Pick label="Registration" value={f.registration} onChange={v => set('registration', v)} options={[{ ...all, label: 'All statuses' }, { value: 'not_registered', label: 'Not registered' }, { value: 'registered', label: 'Registered' }, { value: 'promised', label: 'Promised' }, { value: 'planning', label: 'Planning' }, { value: 'not_planning', label: 'Not planning' }, { value: 'overdue', label: 'Overdue' }]}/><Pick label="Module" value={f.module} onChange={v => set('module', v)} options={[{ ...all, label: 'Any module' }, ...MODULES.map(value => ({ value, label: display(value) }))]}/><Pick label="Module level" value={f.level} onChange={v => set('level', v)} options={[{ ...all, label: 'All levels' }, { value: 'unassessed', label: 'Not assessed' }, ...levelNames.slice(1).map((label, i) => ({ value: String(i + 1), label }))]}/></div>
 {more && <div className="extended-filters"><Pick label="Campus" value={f.branch} onChange={v => set('branch', v)} options={[{ ...all, label: 'All campuses' }, ...data.branches.map(b => ({ value: b.id, label: b.name }))]}/><Pick label="Teacher" value={f.teacher} onChange={v => set('teacher', v)} options={[{ ...all, label: 'All teachers' }, ...data.staff.map(s => ({ value: s.id, label: s.full_name }))]}/><Pick label="Student status" value={f.status} onChange={v => set('status', v)} options={[all, ...['active', 'inactive', 'completed', 'on_hold', 'dropped'].map(value => ({ value, label: display(value) }))]}/><Pick label="Enrollment status" value={f.enrollment} onChange={v => set('enrollment', v)} options={[all, ...['active', 'enrolled', 'completed', 'transferred', 'dropped', 'suspended'].map(value => ({ value, label: display(value) }))]}/><Pick label="Destination country" value={f.country} onChange={v => set('country', v)} options={[{ ...all, label: 'All countries' }, ...Array.from(new Set(data.students.map(s => s.goal.destination_country).filter(Boolean))).sort().map(value => ({ value, label: value }))]}/><Field label="Target intake" type="month" value={f.intake} onChange={v => set('intake', v)}/><Pick label="Target overall band" value={f.target} onChange={v => set('target', v)} options={[all, ...Array.from({ length: 19 }, (_, i) => ({ value: String(i / 2), label: (i / 2).toFixed(1) }))]}/><Pick label="Course history" value={f.source} onChange={v => set('source', v)} options={[all, { value: 'hexas', label: 'Has HEXA’S course history' }, { value: 'external', label: 'Studied at another institute' }, { value: 'new', label: 'No recorded course history' }]}/><Field label="Exam date from" type="date" value={f.examFrom} onChange={v => set('examFrom', v)}/><Field label="Exam date until" type="date" value={f.examTo} onChange={v => set('examTo', v)}/><Field label="Registration date from" type="date" value={f.registerFrom} onChange={v => set('registerFrom', v)}/><Field label="Registration date until" type="date" value={f.registerTo} onChange={v => set('registerTo', v)}/><p className="help span-all">Filters work together. Registration dates use the actual date when available, otherwise the promised date.</p></div>}
 {labels.length > 0 && <div className="active-filters">{labels.map(l => <span key={l}>{l}</span>)}<button onClick={() => onChange({ ...EMPTY_FILTERS })}><X size={14}/> Clear all</button></div>}</div>;
}
