'use client';
import { useState } from 'react';
import { ArrowLeft, Plus, Pencil, Phone, Mail, MapPin, Target, GraduationCap, CalendarDays, MessageSquare, FileDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Student, Snapshot, MODULES, display, dateLabel, intakeLabel, registrationNames, isOverdue, latestAssessment, canCore, canAcademic, canIelts, goalSchema, planSchema, hasInstituteHistory, hicuEnrollments } from './model';
import { StudentReviewCard, WeeklyReviewPanel } from './student-review';
import { Area, Pick } from './fields';
import { ActionDialog, AssessmentDialog, EnrollmentDialog, HistoryDialog } from './dialogs';
import { GoalFields, PlanFields, Mutate } from './student-form';
export function StudentProfile({ student: s, data, onBack, onEdit, onReport, mutate }: {
    student: Student;
    data: Snapshot;
    onBack: () => void;
    onEdit: () => void;
    onReport: () => void;
    mutate: Mutate;
}) {
    const [dialog, setDialog] = useState(''), [goal, setGoal] = useState(s.goal), [plan, setPlan] = useState(s.plan), [note, setNote] = useState(''), [category, setCategory] = useState(data.me?.role === 'front_desk' ? 'general' : data.me?.role === 'counselor' ? 'counseling' : 'academic'), [busy, setBusy] = useState(false), [error, setError] = useState('');
    const role = data.me?.role;
    const a = latestAssessment(s);
    const hasWeeklyReview = hicuEnrollments(s, data).length > 0;
    return <div><Button variant="ghost" className="back-button" onClick={onBack}><ArrowLeft /> Back to students</Button><div className="profile-header"><div className="profile-avatar">{s.full_name.split(' ').map(w => w[0]).slice(0, 2).join('')}</div><div className="profile-title"><p className="eyebrow">{s.student_code}</p><h1>{s.full_name}</h1><div className="profile-meta"><span><Phone />{s.primary_phone}</span><span><MapPin />{data.branches.find(b => b.id === s.primary_branch_id)?.name}</span><span className={'status-badge ' + s.status}>{display(s.status)}</span></div></div><div className="heading-actions"><Button variant="outline" onClick={onReport}><FileDown /> PDF</Button>{canCore(role) && <Button onClick={onEdit}><Pencil /> Edit details</Button>}</div></div>
 <div className="profile-highlights"><div><span>Target overall</span><strong>{s.goal.target_overall?.toFixed(1) || '—'}<small> band</small></strong></div><div><span>Destination</span><strong>{s.goal.destination_country || 'Not set'}</strong></div><div><span>Target intake</span><strong>{intakeLabel(s.goal.intended_intake)}</strong></div><div><span>Registration</span><strong className={isOverdue(s) ? 'text-danger' : ''}>{isOverdue(s) ? 'Overdue' : registrationNames[s.plan.registration_status]}</strong></div></div>
 <Tabs defaultValue="overview"><TabsList variant="line" className="profile-tabs"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="courses"><GraduationCap /> Courses & history</TabsTrigger><TabsTrigger value="academic"><Target /> Academic profile</TabsTrigger>{hasWeeklyReview && <TabsTrigger value="weekly"><CalendarDays /> Weekly review</TabsTrigger>}<TabsTrigger value="ielts"><CalendarDays /> IELTS journey</TabsTrigger><TabsTrigger value="notes"><MessageSquare /> Observations & notes</TabsTrigger></TabsList>
 <TabsContent value="overview"><StudentReviewCard key={s.id} student={s} data={data} mutate={mutate}/><div className="profile-columns"><section className="form-card"><h2>Student details</h2><dl className="detail-list">{[['WhatsApp', s.whatsapp_phone], ['Secondary phone', s.secondary_phone], ['Email', s.email], ['Education', s.education_level], ['Institution', s.institution_name], ['Home district', s.home_district], ['Address', s.address], ['Joined', dateLabel(s.joining_date)], ['Institute student', hasInstituteHistory(s) ? 'Yes — see course history' : 'No recorded HEXA’S course']].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || 'Not recorded'}</dd></div>)}</dl>{s.general_notes && <p className="observation-text">{s.general_notes}</p>}</section><section className="form-card"><div className="section-heading"><h2>Current module levels</h2>{canAcademic(role) && <Button size="sm" variant="outline" onClick={() => setDialog('assessment')}>Update</Button>}</div><ModuleLevels student={s}/><p className="help">Levels 1–5 are staff assessments, separate from IELTS band scores.</p><h3 className="section-small">Latest teacher’s observation</h3><p className="observation-text">{a?.observation || 'No observation recorded yet.'}</p>{a && <p className="help">{a.assessed_by} · {dateLabel(a.created_at.slice(0, 10))}</p>}</section></div></TabsContent>
 <TabsContent value="courses"><section className="form-card"><div className="section-heading"><h2>Course enrollments <span className="count-pill">{s.enrollments.length}</span></h2>{canCore(role) && <Button size="sm" onClick={() => setDialog('enrollment')}><Plus /> Enroll in a batch</Button>}</div>{s.enrollments.length === 0 && <p className="help">No enrollments yet. The student’s profile is ready for a course.</p>}{s.enrollments.map(e => { const b = data.batches.find(b => b.id === e.batch_id), c = data.courses.find(c => c.id === b?.course_type_id); return <div key={e.id} className="enrollment-row"><div className="course-symbol"><GraduationCap /></div><div className="grow"><strong>{c?.name || 'Previous course'}</strong><p>{b?.batch_code || 'Previous batch'} · {dateLabel(e.enrollment_date)}</p>{e.enrollment_notes && <p>{e.enrollment_notes}</p>}</div>{canCore(role) ? <Pick label="Enrollment status" value={e.status} onChange={async (status) => { try {
        await mutate('update_enrollment', { id: e.id, student_id: s.id, status });
    }
    catch (er) {
        setError(er instanceof Error ? er.message : 'Could not update enrollment.');
    } }} options={['enrolled', 'active', 'completed', 'transferred', 'dropped', 'suspended'].map(value => ({ value, label: display(value) }))}/> : <span className="status-badge">{display(e.status)}</span>}</div>; })}</section><section className="form-card"><div className="section-heading"><h2>Previous courses & institutes</h2>{canCore(role) && <Button size="sm" variant="outline" onClick={() => setDialog('history')}><Plus /> Add previous course</Button>}</div>{s.history.length === 0 && <p className="help">No previous course history recorded.</p>}{s.history.map(h => <div className="history-row" key={h.id}><span className={'status-badge ' + (h.institution_type === 'hexas' ? 'blue' : 'neutral')}>{h.institution_type === 'hexas' ? 'HEXA’S' : 'External institute'}</span><strong>{h.course_name}</strong><p>{h.institution_name}{h.batch_name && ' · ' + h.batch_name}{h.completion_date && ' · Completed ' + dateLabel(h.completion_date)}</p>{h.notes && <p>{h.notes}</p>}</div>)}</section></TabsContent>
 <TabsContent value="academic"><section className="form-card"><div className="section-heading"><h2>Academic progress</h2>{canAcademic(role) && <Button size="sm" onClick={() => setDialog('assessment')}><Plus /> Record assessment</Button>}</div>{s.assessments.length === 0 && <p className="help">Record the first assessment to track module levels over time.</p>}{s.assessments.map(a => <article className="assessment-card" key={a.id}><div className="section-heading"><strong>{dateLabel(a.created_at.slice(0, 10))}</strong><span className="help">{a.assessed_by}</span></div><div className="assessment-grid">{MODULES.map(m => <div key={m}><span>{display(m)}</span><strong>{a.levels[m] ?? '—'}<small> / 5</small></strong><p>Estimated band: {a.bands[m]?.toFixed(1) || 'Not set'}</p></div>)}</div>{a.observation && <p className="observation-text">{a.observation}</p>}</article>)}</section></TabsContent>
 {hasWeeklyReview && <TabsContent value="weekly"><WeeklyReviewPanel key={s.id} student={s} data={data} mutate={mutate}/></TabsContent>}
 <TabsContent value="ielts"><div className="profile-columns"><section className="form-card"><div className="section-heading"><h2>Goals & destination</h2>{canIelts(role) && <Button size="sm" variant="outline" onClick={() => { setGoal(s.goal); setDialog('goal'); }}>Edit goals</Button>}</div><dl className="detail-list">{[['Overall target', s.goal.target_overall?.toFixed(1)], ...MODULES.map(m => [display(m) + ' target', s.goal[`target_${m}`]?.toFixed(1)]), ['Country', s.goal.destination_country], ['Intake', intakeLabel(s.goal.intended_intake)], ['Study level', s.goal.study_level], ['Purpose', s.goal.purpose]].map(([l, v]) => <div key={l}><dt>{l}</dt><dd>{v || 'Not set'}</dd></div>)}</dl>{s.goal.goal_notes && <p className="observation-text">{s.goal.goal_notes}</p>}</section><section className="form-card"><div className="section-heading"><h2>Exam & registration</h2>{canIelts(role) && <Button size="sm" variant="outline" onClick={() => { setPlan(s.plan); setDialog('plan'); }}>Update plan</Button>}</div><span className={'status-badge ' + (isOverdue(s) ? 'overdue' : s.plan.registration_status)}>{isOverdue(s) ? 'Registration overdue' : registrationNames[s.plan.registration_status]}</span><dl className="detail-list">{[['Intended exam', dateLabel(s.plan.intended_exam_date)], ['Intended month', intakeLabel(s.plan.intended_exam_month)], ['Promised registration', dateLabel(s.plan.promised_registration_date)], ['Registered on', dateLabel(s.plan.actual_registration_date)], ['Confirmed exam', dateLabel(s.plan.actual_exam_date)], ['Exam type', s.plan.exam_type], ['Format', s.plan.exam_format], ['Provider', s.plan.provider], ['Test centre', s.plan.test_centre], ['Candidate reference', s.plan.candidate_reference]].map(([l, v]) => <div key={l}><dt>{l}</dt><dd>{v || 'Not set'}</dd></div>)}</dl>{s.plan.notes && <p className="observation-text">{s.plan.notes}</p>}</section></div></TabsContent>
 <TabsContent value="notes"><section className="form-card"><h2>Teacher’s observations & student notes</h2>{role && role !== 'viewer' && <form className="note-form" onSubmit={async (e) => { e.preventDefault(); if (!note.trim())
        return; setBusy(true); setError(''); try {
        await mutate('add_note', { student_id: s.id, note, category, visibility: 'normal' });
        setNote('');
    }
    catch (er) {
        setError(er instanceof Error ? er.message : 'Could not save note.');
    }
    finally {
        setBusy(false);
    } }}><Pick label="Note type" value={category} onChange={setCategory} options={(role === 'teacher' ? ['academic', 'general'] : role === 'front_desk' ? ['general'] : role === 'counselor' ? ['counseling', 'exam', 'general'] : ['academic', 'counseling', 'exam', 'general']).map(value => ({ value, label: display(value) }))}/><Area label="Observation / note" value={note} onChange={setNote} placeholder="Write your observation about the student…"/><Button disabled={busy || !note.trim()}>{busy ? 'Saving…' : 'Add note'}</Button></form>}{s.notes.length === 0 && <p className="help">No notes yet. Academic assessment observations appear in the Academic profile tab.</p>}{s.notes.map(n => <article className="note" key={n.id}><span className="status-badge neutral">{display(n.category)}</span><p>{n.note}</p><small>{n.author_name} · {dateLabel(n.created_at.slice(0, 10))}</small></article>)}</section></TabsContent></Tabs>{error && <p role="alert" className="error-banner">{error}</p>}
 {dialog === 'enrollment' && <EnrollmentDialog student={s} data={data} onClose={() => setDialog('')} mutate={mutate}/>} {dialog === 'history' && <HistoryDialog student={s} onClose={() => setDialog('')} mutate={mutate}/>} {dialog === 'assessment' && <AssessmentDialog student={s} data={data} onClose={() => setDialog('')} mutate={mutate}/>}
 {dialog === 'goal' && <ActionDialog title="Edit IELTS goals" onClose={() => setDialog('')} onSave={async () => { goalSchema.parse(goal); await mutate('save_goal', { student_id: s.id, ...goal }); }}><GoalFields value={goal} onChange={setGoal}/></ActionDialog>}
 {dialog === 'plan' && <ActionDialog title="Update exam & registration" onClose={() => setDialog('')} onSave={async () => { planSchema.parse(plan); await mutate('save_plan', { student_id: s.id, ...plan }); }}><PlanFields value={plan} onChange={setPlan}/></ActionDialog>}
 </div>;
}
export function ModuleLevels({ student: s }: {
    student: Student;
}) { const levels = latestAssessment(s)?.levels; return <div className="module-levels">{MODULES.map(m => <div key={m}><span>{display(m)}</span><div className="level-track">{[1, 2, 3, 4, 5].map(i => <i key={i} className={levels?.[m] != null && i <= levels[m]! ? `filled level-${levels[m]}` : ''}/>)}</div><strong>{levels?.[m] ?? '—'}<small> / 5</small></strong></div>)}</div>; }
