-- HEXUS / HEXA'S Student Desk. Additive foundation for the current requested workflows.
-- Supabase PostgreSQL; all browser access uses Auth + RLS, never a service-role key.
begin;
create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;
create domain public.ielts_band as numeric(2,1) check(value between 0 and 9 and mod(value,0.5)=0);
create domain public.module_level as smallint check(value between 1 and 5);
create table public.roles(id uuid primary key default gen_random_uuid(),name text not null unique,description text);
insert into public.roles(name) values ('super_admin'),('branch_manager'),('academic_coordinator'),('teacher'),('counselor'),('front_desk'),('viewer');
create table public.branches(id uuid primary key default gen_random_uuid(),name text not null,code text not null unique,address text default '',phone text default '',email text default '',is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id),full_name text not null,phone text default '',branch_id uuid references public.branches(id),role_id uuid references public.roles(id),is_active boolean not null default false,avatar_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.user_branch_access(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id),branch_id uuid not null references public.branches(id),created_at timestamptz not null default now(),unique(user_id,branch_id));
create sequence public.student_code_sequence;
create table public.students(id uuid primary key default gen_random_uuid(),student_code text not null unique,full_name text not null check(length(trim(full_name)) between 2 and 300),primary_phone text not null,whatsapp_phone text not null default '',secondary_phone text not null default '',email text not null default '',gender text default '',date_of_birth date,occupation text default '',education_level text not null default '',institution_name text not null default '',address text not null default '',home_district text not null default '',primary_branch_id uuid not null references public.branches(id),joining_date date,student_source text default '',source_details text default '',profile_photo_url text,status text not null default 'active' check(status in ('active','inactive','completed','dropped','on_hold')),general_notes text not null default '',created_by uuid references public.profiles(id) default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table public.course_types(id uuid primary key default gen_random_uuid(),name text not null,short_code text not null unique,category text not null default '',description text not null default '',default_duration_days integer check(default_duration_days>0),attendance_enabled boolean not null default true,assessment_enabled boolean not null default true,mock_test_enabled boolean not null default true,ielts_tracking_enabled boolean not null default false,result_tracking_enabled boolean not null default false,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.batches(id uuid primary key default gen_random_uuid(),course_type_id uuid not null references public.course_types(id),branch_id uuid not null references public.branches(id),batch_code text not null unique,name text not null default '',teacher_id uuid references public.profiles(id),assistant_teacher_id uuid references public.profiles(id),coordinator_id uuid references public.profiles(id),start_date date,end_date date,class_days jsonb not null default '[]',start_time time,end_time time,room text not null default '',maximum_capacity integer check(maximum_capacity>0),status text not null default 'planned' check(status in ('planned','open','running','completed','cancelled')),notes text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date is null or start_date is null or end_date>=start_date),check(end_time is null or start_time is null or end_time>start_time));
create table public.enrollments(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id),batch_id uuid not null references public.batches(id),enrollment_date date not null default current_date,status text not null default 'active' check(status in ('enrolled','active','completed','transferred','dropped','suspended')),previous_hexus_student boolean not null default false,previous_hexus_branch_id uuid references public.branches(id),previous_course_name text not null default '',previous_batch_name text default '',enrollment_notes text not null default '',created_by uuid references public.profiles(id) default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index enrollment_one_active_per_batch on public.enrollments(student_id,batch_id) where status in ('active','enrolled');
create table public.student_ielts_goals(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id),enrollment_id uuid references public.enrollments(id),target_overall public.ielts_band,target_listening public.ielts_band,target_reading public.ielts_band,target_writing public.ielts_band,target_speaking public.ielts_band,destination_country text not null default '',study_level text not null default '',intended_intake text not null default '' check(intended_intake='' or intended_intake ~ '^\d{4}-(0[1-9]|1[0-2])$'),intended_exam_month date,preferred_exam_date date,purpose text not null default '',goal_notes text not null default '',is_current boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index goal_one_current on public.student_ielts_goals(student_id) where is_current;
create table public.exam_plans(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id),enrollment_id uuid references public.enrollments(id),status text not null default 'no_plan',intended_exam_date date,intended_exam_month date,exam_type text not null default 'IELTS Academic',exam_format text not null default 'Computer',provider text not null default '',intended_test_centre text not null default '',planning_notes text not null default '',is_current boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index plan_one_current on public.exam_plans(student_id) where is_current;
create table public.exam_registrations(id uuid primary key default gen_random_uuid(),exam_plan_id uuid not null references public.exam_plans(id),student_id uuid not null references public.students(id),registration_status text not null default 'not_planning' check(registration_status in ('not_planning','planning','promised','registered')),promised_registration_date date,followup_date date,actual_registration_date date,actual_exam_date date,provider text not null default '',test_centre text not null default '',candidate_reference text not null default '',notes text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(registration_status<>'registered' or actual_registration_date is not null),check(registration_status<>'promised' or promised_registration_date is not null),check(actual_exam_date is null or actual_registration_date is null or actual_exam_date>=actual_registration_date),unique(exam_plan_id));
-- General module assessments support every customizable course; no course-specific fields are put in students.
create table public.student_assessments(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id),enrollment_id uuid references public.enrollments(id),listening_level public.module_level,reading_level public.module_level,writing_level public.module_level,speaking_level public.module_level,listening_band public.ielts_band,reading_band public.ielts_band,writing_band public.ielts_band,speaking_band public.ielts_band,observation text not null default '',assessed_by uuid references public.profiles(id) default auth.uid(),created_at timestamptz not null default now());
create table public.student_course_history(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id),institution_type text not null check(institution_type in ('hexas','external')),institution_name text not null check(length(trim(institution_name))>0),course_name text not null check(length(trim(course_name))>0),batch_name text not null default '',completion_date date,notes text not null default '',created_by uuid references public.profiles(id) default auth.uid(),created_at timestamptz not null default now());
create table public.student_notes(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id),enrollment_id uuid references public.enrollments(id),category text not null default 'general' check(category in ('academic','counseling','attendance','exam','management','general')),note text not null check(length(trim(note)) between 1 and 10000),visibility text not null default 'normal' check(visibility in ('normal','management_only')),author_id uuid references public.profiles(id) default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.audit_logs(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) default auth.uid(),action text not null,table_name text not null,record_id uuid,old_values jsonb,new_values jsonb,created_at timestamptz not null default now());
create index students_branch_idx on public.students(primary_branch_id);create index students_status_idx on public.students(status);create index students_phone_idx on public.students(primary_phone);create index students_whatsapp_idx on public.students(whatsapp_phone);create index students_secondary_idx on public.students(secondary_phone);create index students_email_idx on public.students(lower(email));create index students_name_idx on public.students(lower(full_name));
create index batches_course_idx on public.batches(course_type_id);create index batches_branch_idx on public.batches(branch_id);create index batches_teacher_idx on public.batches(teacher_id);create index enrollments_student_idx on public.enrollments(student_id);create index enrollments_batch_idx on public.enrollments(batch_id);create index enrollments_status_idx on public.enrollments(status);
create index assessments_student_idx on public.student_assessments(student_id,created_at desc);create index history_student_idx on public.student_course_history(student_id);create index notes_student_idx on public.student_notes(student_id,created_at desc);create index exam_plans_student_idx on public.exam_plans(student_id);create index registrations_status_idx on public.exam_registrations(registration_status);create index registrations_promised_idx on public.exam_registrations(promised_registration_date);create index registrations_student_idx on public.exam_registrations(student_id);

create function private.desk_role() returns text language sql stable security definer set search_path='' as $$select r.name from public.profiles p join public.roles r on r.id=p.role_id where p.id=auth.uid() and p.is_active$$;
create function private.desk_can_branch(bid uuid) returns boolean language sql stable security definer set search_path='' as $$select coalesce(private.desk_role()='super_admin' or (private.desk_role() is not null and (exists(select 1 from public.profiles p where p.id=auth.uid() and p.branch_id=bid) or exists(select 1 from public.user_branch_access a where a.user_id=auth.uid() and a.branch_id=bid))),false)$$;
create function private.desk_can_student(sid uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.students s where s.id=sid and s.deleted_at is null and (private.desk_role()='super_admin' or (private.desk_role()='teacher' and exists(select 1 from public.enrollments e join public.batches b on b.id=e.batch_id where e.student_id=s.id and (b.teacher_id=auth.uid() or b.assistant_teacher_id=auth.uid()))) or (private.desk_role() is not null and private.desk_role()<>'teacher' and (private.desk_can_branch(s.primary_branch_id) or exists(select 1 from public.enrollments e join public.batches b on b.id=e.batch_id where e.student_id=s.id and private.desk_can_branch(b.branch_id))))))$$;
create function private.desk_phone(v text) returns text language plpgsql immutable set search_path='' as $$declare n text;begin n:=regexp_replace(translate(coalesce(v,''),'০১২৩৪৫৬৭৮৯','0123456789'),'[^0-9+]','','g');if n like '00880%' then n:='+'||substring(n from 3);end if;if n ~ '^01[3-9][0-9]{8}$' then n:='+88'||n;end if;if n ~ '^8801[3-9][0-9]{8}$' then n:='+'||n;end if;return n;end$$;
create function private.desk_student_before_write() returns trigger language plpgsql security definer set search_path='' as $$declare bc text;begin
 perform pg_advisory_xact_lock(7320126);
 new.primary_phone:=private.desk_phone(new.primary_phone);new.whatsapp_phone:=private.desk_phone(new.whatsapp_phone);new.secondary_phone:=private.desk_phone(new.secondary_phone);new.email:=lower(trim(new.email));
 if new.primary_phone !~ '^\+?[0-9]{7,15}$' or (new.whatsapp_phone<>'' and new.whatsapp_phone !~ '^\+?[0-9]{7,15}$') or (new.secondary_phone<>'' and new.secondary_phone !~ '^\+?[0-9]{7,15}$') then raise exception 'Enter a valid phone number.';end if;
 if new.email<>'' and new.email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then raise exception 'Enter a valid email address.';end if;
 if exists(select 1 from public.students s where s.id<>new.id and s.deleted_at is null and (s.primary_phone=any(array_remove(array[new.primary_phone,new.whatsapp_phone,new.secondary_phone],'')) or s.whatsapp_phone<>'' and s.whatsapp_phone=any(array_remove(array[new.primary_phone,new.whatsapp_phone,new.secondary_phone],'')) or s.secondary_phone<>'' and s.secondary_phone=any(array_remove(array[new.primary_phone,new.whatsapp_phone,new.secondary_phone],'')) or new.email<>'' and lower(s.email)=new.email)) then raise exception 'A student with this phone number or email already exists. Open the existing student or contact an administrator.';end if;
 if tg_op='INSERT' then select b.code into bc from public.branches b where b.id=new.primary_branch_id;new.student_code:='HEX-'||bc||'-'||extract(year from current_date)::text||'-'||lpad(nextval('public.student_code_sequence')::text,5,'0');else new.student_code:=old.student_code;end if;
 new.updated_at:=clock_timestamp();return new;end$$;
create trigger students_validate before insert or update on public.students for each row execute function private.desk_student_before_write();
create function private.desk_profile_on_signup() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,full_name,role_id,is_active) values(new.id,left(coalesce(nullif(new.raw_user_meta_data->>'full_name',''),split_part(new.email,'@',1),'Staff member'),300),(select id from public.roles where name='viewer'),false);return new;end$$;
create trigger desk_auth_signup after insert on auth.users for each row execute function private.desk_profile_on_signup();

-- Direct browser writes are revoked. All writes use desk_write, with explicit role/branch checks.
-- Read policies remain authoritative for RPC snapshots and direct PostgREST reads.
alter table public.roles enable row level security;alter table public.branches enable row level security;alter table public.profiles enable row level security;alter table public.user_branch_access enable row level security;alter table public.students enable row level security;alter table public.course_types enable row level security;alter table public.batches enable row level security;alter table public.enrollments enable row level security;alter table public.student_ielts_goals enable row level security;alter table public.exam_plans enable row level security;alter table public.exam_registrations enable row level security;alter table public.student_assessments enable row level security;alter table public.student_course_history enable row level security;alter table public.student_notes enable row level security;alter table public.audit_logs enable row level security;
create policy roles_read on public.roles for select to authenticated using(true);
create policy branches_read on public.branches for select to authenticated using(private.desk_can_branch(id));
create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or private.desk_role()='super_admin' or private.desk_can_branch(branch_id));
create policy branch_access_read on public.user_branch_access for select to authenticated using(user_id=auth.uid() or private.desk_role()='super_admin');
create policy students_read on public.students for select to authenticated using(private.desk_can_student(id));
create policy courses_read on public.course_types for select to authenticated using(private.desk_role() is not null);
create policy batches_read on public.batches for select to authenticated using(private.desk_role()='super_admin' or private.desk_role()='teacher' and (teacher_id=auth.uid() or assistant_teacher_id=auth.uid()) or private.desk_role()<>'teacher' and private.desk_can_branch(branch_id));
create policy enrollments_read on public.enrollments for select to authenticated using(private.desk_can_student(student_id) and (private.desk_role()<>'teacher' or exists(select 1 from public.batches b where b.id=batch_id and (b.teacher_id=auth.uid() or b.assistant_teacher_id=auth.uid()))));
create policy goals_read on public.student_ielts_goals for select to authenticated using(private.desk_can_student(student_id));
create policy plans_read on public.exam_plans for select to authenticated using(private.desk_can_student(student_id));
create policy registrations_read on public.exam_registrations for select to authenticated using(private.desk_can_student(student_id));
create policy assessments_read on public.student_assessments for select to authenticated using(private.desk_can_student(student_id));
create policy history_read on public.student_course_history for select to authenticated using(private.desk_can_student(student_id));
create policy notes_read on public.student_notes for select to authenticated using(private.desk_can_student(student_id) and (visibility='normal' or private.desk_role() in ('super_admin','branch_manager')));
create policy audit_read on public.audit_logs for select to authenticated using(private.desk_role()='super_admin');
revoke all on public.roles,public.branches,public.profiles,public.user_branch_access,public.students,public.course_types,public.batches,public.enrollments,public.student_ielts_goals,public.exam_plans,public.exam_registrations,public.student_assessments,public.student_course_history,public.student_notes,public.audit_logs from anon,authenticated;
grant select on public.roles,public.branches,public.profiles,public.user_branch_access,public.students,public.course_types,public.batches,public.enrollments,public.student_ielts_goals,public.exam_plans,public.exam_registrations,public.student_assessments,public.student_course_history,public.student_notes,public.audit_logs to authenticated;
commit;
